#!/bin/bash


# run the custom setup from github

BASH_CUSTOM="$HOME/dotfiles/bash-custom"

[ -f ${BASH_CUSTOM} ] && . ${BASH_CUSTOM}

# environment variables unique to this machine

# aliases unique to this machine

