silent! execute pathogen#infect() " for Pathogen

syntax on

let g:netrw_liststyle = 3 " netrw browser settings
let g:netrw_altv = 1
let g:netrw_banner = 0

filetype plugin on
filetype indent on

set so=7                " start vertical scroll from 7 lines

try
    colorscheme darkblue
catch
endtry

set background=dark
set autochdir 		    " change directory to the current buffer when opening files.
"set cursorline		    " display a line under the cursor 
set wildmenu
set wildmode=full
set lazyredraw
set nocompatible
set nu                  " line numbers
set clipboard=unnamed
set ruler               " show the cursor position all the time
"set laststatus=2 	    " always show the status line
set statusline=%f       " Path to the file
set statusline+=%=      " Switch to the right side
set statusline+=%l      " Current line
set statusline+=/       " Separator
set statusline+=%L      " Total lines

set showmatch           " highlight matching brackets
set mat=2               " how many tenths of a second to blink when matching brackets

set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set smartcase           " when searching try to be smart about cases 

set backup		
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup

set tabstop=4           " number of visual spaces per TAB
set softtabstop=4       " number of spaces in tab when editing
set expandtab           " tabs are spaces

set foldcolumn=1
set ai                  " auto indent
set si                  " smart indent
"set wrap               " wrap lines
set viminfo^=%          " remember info about open buffers on close

au BufNewFile,BufRead *.gradle setf groovy
autocmd BufNewFile,BufRead *.json set ft=javascript

" map <Space> to / (search) and Ctrl-<Space> to ? (backwards search)
map <space> }
" Disable highlight when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>
" to exit insert mode
inoremap § <esc>

if has('mouse')
        set mouse=a
endif

" disable dope keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
noremap h <NOP>
noremap l <NOP>

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif
