#!/bin/bash

# Parse git branch
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

echoRun () {
  echo $@
  eval $@
  echo $@
}

# Set JDK via JAVA_HOME
function setjdk() {  
	if [ $# -ne 0 ]; then  
		removeFromPath '/System/Library/Frameworks/JavaVM.framework/Home/bin'  
		if [ -n "${JAVA_HOME+x}" ]; then  
			removeFromPath $JAVA_HOME  
		fi  
		export JAVA_HOME=`/usr/libexec/java_home -v $@`  
		export PATH=$JAVA_HOME/bin:$PATH  
	fi  
}  

function removeFromPath() {  
	export PATH=$(echo $PATH | sed -E -e "s;:$1;;" -e "s;$1:?;;")  
}

# General
alias clp='pbcopy <'
alias c='/bin/clear'
alias clea='/bin/clear'
alias cl='/bin/clear'
alias h='history'
alias v='/bin/vim'
alias vp='if [ -e pom.xml ]; then vim pom.xml; else echo "No pom in pwd"; fi'
alias s='/bin/clear'
alias apps="cd /c/apps"
alias p='/bin/pwd'
alias pw='/bin/pwd'
alias wpd='/bin/pwd'
alias dpw='/bin/pwd'

# grep
alias grs='/bin/grep -l -r'

# push
alias pd='pushd ./'
alias dp='popd'

# ls
alias l='/bin/ls -lah'
alias sl='/bin/ls -lah'
alias ll='/bin/ls -lah'
alias la='/bin/ls -lah'

# git
alias g='/bin/git'
alias gs='git status --short'
alias gg='git grep'
alias gl='git ls-files'
alias gls='git ls-files'

# Prompt stuff
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$(parse_git_branch) "
export CLICOLOR=1
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

# LS colours
export LSCOLORS=ExFxBxDxCxegedabagacad

setjdk 1.7
